### ISSUE TITLE
Makefile doesn't copy the files .bst e .bib at install

### ISSUE THREAD

**Issue by bombardellif** [schnorr/infufrgs#34]
In the Makefile, the commands to copy the **bst** and the **bib** files to the install directory are missing. I had to add them at my fork, so that the abntex library works.

Can someone tell, whether it is correct as it is now? Or should the Makefile be changed?

Check out my version at [https://github.com/bombardellif/iiufrgs/blob/master/Makefile](https://github.com/bombardellif/iiufrgs/blob/master/Makefile).

**Comment by mgmillani** [comment]
I think your modifications are correct, but I would use `mv $(INPUTS)/*.bst ($BST)` (and the same for .bib) instead . This way we don't end up with duplicates.

**Comment by schnorr** [comment]
Dear @bombardellif thanks for reporting the issue. Could you check if commit f4aa59eb8c3b63a15e4b610529b3405e656dae90 fix the issue and re-open it if there is still a problem? Thanks again!
