### ISSUE TITLE
Et al nas referências

### ISSUE THREAD

**Issue by rafaelcp** [schnorr/infufrgs#40]
Uma integrante da minha banca de defesa de tese apontou para o fato de que estão aparecendo "et al's" nas referências (não nos pontos de citação), quando o correto, nesta área, seria mostrar sempre todos os autores. Bug ou intended?

**Comment by schnorr** [comment]
Se me lembro bem, isso é assim para respeitar as regras da biblioteca.

**Comment by mgmillani** [comment]
Dei uma olhada nos documentos de exemplo da biblioteca e em nem lugar eles mencionam o uso de et al. Infelizmente há apenas referências com no máximo três autores, e o iiufrgs usa et al apenas a partir de quatro.

Não tenho certeza qual a regra oficial quanto a isso, mas se tu precisares mudar urgentemente, é possível colocar duas chaves para os autores no .bib e fazer a formatação a mão (isto é, `author = {{ALMEIDA, J.}}` em vez de `author = {João Almeida}`).

Será que alguém da UFRGS poderia verificar com a biblioteca como que deve ser feito? Acho difícil de acreditar que se deva usar et al em referências. Como a formatação dos autores é igual em citações e referências, pode ser um bug mesmo.

Vou reabrir já que não temos certeza se é um bug ou não.

**Comment by vfbsilva** [comment]
@rafaelcp tem como enviar esse PR?

**Comment by vfbsilva** [comment]
@schnorr já tratei isso no meu último PR

**Comment by schnorr** [comment]
@vfbsilva Não encontrei teu PR tratando do problema do `et al`.

**Comment by vfbsilva** [comment]
@schnorr não sou mega entendido em git. vejamos eu arrumei no 486bb8b antes de arrumar os warnings então se aceitar o último PR já deve vir com tudo.

**Comment by schnorr** [comment]
Por enquanto não tenho informação que essa modificação é uma demanda da biblioteca. Estou fechando a issue, podemos reabrí-la caso necessário.
