### ISSUE TITLE
Erro ao instalar

### ISSUE THREAD

**Issue by nkatte** [schnorr/infufrgs#48]
O Makefile espera um arquivo markdown
https://github.com/schnorr/infufrgs/blob/7e4f188be7cbf6a8fcdfd52c4e55b224ed8f0d72/Makefile#L32
porém o commit f5ccc5532a9cf51fe97e4438ba4e89f08e1348d1 renomeou o arquivo __README__ de __.md__ para __.org__, ocasionando erro na instalação.

```bash
[nkatte@Kun infufrgs]$ make INSTALLDIR="./build" install
install -d ./build/tex/latex/iiufrgs ./build/doc/latex/iiufrgs ./build/bibtex/bst
cp -R inputs/* ./build/tex/latex/iiufrgs
cp README.md COPYING CHANGELOG ./build/doc/latex/iiufrgs
cp: cannot stat 'README.md': No such file or directory
make: *** [Makefile:32: install] Error 1
```

**Comment by schnorr** [comment]
Veja se 0b70361ef0c23d500f26d9b63806cba6b60665f6 resolve.
