### ISSUE TITLE
Suporte para sobrescrever o orientadorname

### ISSUE THREAD

**Issue by mathiasgheno** [schnorr/infufrgs#74]
Eu gostaria de poder trocar a descrição de "orientador" no template por "orientadora".

Não achei um meio de fazer isso.

Seria possível a alteração através de um `renewcommand`?

**Comment by schnorr** [comment]
No arquivo `brazilian.babel`, tem uma linha assim:

        `\def\advisorname{Orientador}%`

Substitua-a por:

        `\def\advisorname{Orientadora}%`
