### ISSUE TITLE
Atualização ABNT NBR 10520:2023

### ISSUE THREAD

**Issue by LucasAlegre** [schnorr/infufrgs#85]
A ABNT atualizou várias normas recentemente, sendo a mais significativa a mudança na caixa alta da citação. 

Por exemplo: (SILVA, 2023) para (Silva, 2023)

Um issue já foi aberto no abntex2 (https://github.com/abntex/abntex2/issues/260), onde também se encontram mais detalhes das outras mudanças. Porém, não tenho ideia de quando e se alguém vai implementá-las.

**Comment by daniellumertz** [comment]
Para atualizar o formato de citação é bem simples, só alterar, no arquivo abntex2-alf.bst a linha `#0 'abnt.cite.style :=` para `#1 'abnt.cite.style :=`

**Comment by lukas0459** [comment]
> Para atualizar o formato de citação é bem simples, só alterar, no arquivo abntex2-alf.bst, a linha `#0 'abnt.cite.style :=`, para `#1 'abnt.cite.style :=`

Cara, você salvou muito eu e minha dissertação

**Comment by daniellumertz** [comment]
> > Para atualizar o formato de citação é bem simples, só alterar, no arquivo abntex2-alf.bst, a linha `#0 'abnt.cite.style :=`, para `#1 'abnt.cite.style :=`
> 
> Cara, você salvou muito eu e minha dissertação

De nada camarada!
